In [ ]:
g=np.sum((A,B),axis=0)#columns first
print(g)

[[3 3]
 [7 7]]


In [ ]:
g=np.sum((A,B),axis=1)#ROWS FIRST
print(g)

[[4 4]
 [6 6]]


In [ ]:
import numpy as np


In [ ]:
!pip install np

  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13658 sha256=062c2808b4d5fd7a6698848959412c48a5210300605d2c72822a8c89ae37f00e
  Stored in directory: /root/.cache/pip/wheels/f9/e1/79/c4580a03022dece233bc146286fc9082a8885ee1a7c8d8b980
Successfully built np


In [ ]:
#creating 3-D array
C=np.array([[[2,3,4],[5,6,7]],[[1,8,9],[0,4,5]]])
print(C)



[[[2 3 4]
  [5 6 7]]

 [[1 8 9]
  [0 4 5]]]


In [ ]:
#checking dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

NameError: name 'a' is not defined

In [ ]:
d=np.array([[2,3,5],[7,8,9]])
print(d)

[[2 3 5]
 [7 8 9]]


In [ ]:
A=np.array([[1,1],[3,3]])
B=np.array([[2,2],[4,4]])
print(A*B)

[[ 2  2]
 [12 12]]


In [ ]:
#arange
b=np.arange(3,31,3)
print(b)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#ones
e=np.ones((3,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#zeros
f=np.zeros((4,4))
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#linspace
r=np.linspace(24,10,3)
print(r)

[24. 17. 10.]


In [ ]:
l=np.arange(2,12)
print(l)

[ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
g=np.sum((b,h))
print(g)

330


In [ ]:
y=np.arange(1,7).reshape(2,3)
print(y)
q=np.arange(9,15).reshape(2,3)
print(q)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
#linespace
o=np.linspace(1,2,6)
print(o)

[1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
h=np.arange(3,31,3).reshape(5,2)
print(h)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
!pip install np

  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13658 sha256=69fb655ffff984f177c46836accf78df7c90d9343252ba851120120a09eaab20
  Stored in directory: /root/.cache/pip/wheels/f9/e1/79/c4580a03022dece233bc146286fc9082a8885ee1a7c8d8b980
Successfully built np


In [ ]:
#creating 1d array
A = np.array([2,3,4,5,6])
print(type(A))<

<class 'numpy.ndarray'>


In [ ]:
#creating a 2d array
b=np.array([[2,3,4],[4,5,6]])
print(b)

[[2 3 4]
 [4 5 6]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("output of dstack")
print(np.dstack(a))
#noof rows becomes noof groups
#colums becomes rows
#group becomes columns

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
output of dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


b=np.array(25,289,361,81)#find square rooots and iterate through the results values output:5 square is 25

In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print(np.sqrt(i),"square is",i)


5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81


In [ ]:
#array joins
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b))) #columns
print("\n")

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]




In [ ]:
#array joins
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.hstack((a,b))) #rows
print("\n")

[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]




In [ ]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(a,b)

[[34 35 36]
 [37 38 39]] [[4 5 6]
 [7 8 9]]


In [ ]:
#creating a 3d array
c=np.array([[[2,3,4],[4,5,6]],[[8,9,1],[3,2,1]]])
print(c)

[[[2 3 4]
  [4 5 6]]

 [[8 9 1]
  [3 2 1]]]


In [ ]:
#checking dimensions
p

In [ ]:
import numpy as np